// <auto-generated />
using System;
using ItemsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItemsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItemsApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "ทดสอบ",
                            CreatedDate = new DateTime(2025, 6, 7, 17, 44, 11, 222, DateTimeKind.Local).AddTicks(842),
                            Description = "รายการทดสอบแรก",
                            IsActive = true,
                            Name = "รายการที่ 1",
                            Price = 100.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = "ทดสอบ",
                            CreatedDate = new DateTime(2025, 6, 7, 17, 44, 11, 222, DateTimeKind.Local).AddTicks(1066),
                            Description = "รายการทดสอบที่สอง",
                            IsActive = true,
                            Name = "รายการที่ 2",
                            Price = 200.00m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            Category = "สินค้า",
                            CreatedDate = new DateTime(2025, 6, 7, 17, 44, 11, 222, DateTimeKind.Local).AddTicks(1068),
                            Description = "สินค้าคุณภาพสูง",
                            IsActive = true,
                            Name = "สินค้า A",
                            Price = 500.00m,
                            Quantity = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
